### Sans Traefik ###

#services:
#  it-tools:
#    image: corentinth/it-tools:latest
#    container_name: it-tools
#    ports:
#      - '9825:80'
#    restart: unless-stopped


### Avec Traefik ###
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    networks:
      - traefik-net
    ports:
      - '9825:80'   # accès direct de secours (IP:port), le temps de mettre en place Technitium
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.lab`)"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik-net:
    external: true
