## Sans Traefik ###

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "4457:3000"
    environment:
      - TZ=Europe/Paris
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change_moi
      # - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app  # pour connecter Zabbix, voir plus bas
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
