### Sans Traefik ###
#services:
#  excalidraw:
#    image: excalidraw/excalidraw:latest
#    container_name: excalidraw
#    restart: unless-stopped
#    ports:
#      - "9731:80"
#    environment:
#      - TZ=Europe/Paris

### Avec Traefik ###
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - "9731:80"   # accès direct de secours (IP:port), le temps de mettre en place Technitium
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.lab`)"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
