## Avec Traefik ###
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - "3010:3000"   # accès direct de secours (IP:port), le temps de mettre en place Technitium
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=homepage.lab
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.lab`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  traefik-net:
    external: true
