## Sans Traefik ###
services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    restart: unless-stopped
    ports:
      - "5462:8080"
      # - "8443:8443"   # décommente si tu veux le HTTPS interne du conteneur
    environment:
      - TZ=Europe/Paris
      # - DRAWIO_BASE_URL=https://drawio.tondomaine.fr   # utile si derrière reverse proxy
    volumes:
      - drawio_data:/var/lib/drawio
