### Sans Traefik ###
#services:
#  convertx:
#    image: ghcr.io/c4illin/convertx
#    container_name: convertx
#    restart: unless-stopped
#    ports:
#      - "3001:3000"
#    environment:
#      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234
#      - HTTP_ALLOWED=true
#    volumes:
#      - ./data:/app/data

### Avec Traefik ###
services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - "3001:3000"   # accès direct de secours (IP:port), le temps de mettre en place Technitium
    environment:
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() if unset
      - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.rule=Host(`convertx.lab`)"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"

networks:
  traefik-net:
    external: true
