### Sans Traefik ###
#services:
#  ffmpeg-web:
#    # Build direct depuis le dépôt GitHub, pas besoin de cloner à la main
#    build:
#      context: https://github.com/dinoosauro/ffmpeg-web.git#main
#    container_name: ffmpeg-web
#    ports:
#      - "9831:3000"   # HTTP -> http://localhost:9831
#      # - "3443:443" # Décommenter si tu actives le HTTPS
#    restart: unless-stopped

### Avec Traefik ###
services:
  ffmpeg-web:
    # Build direct depuis le dépôt GitHub, pas besoin de cloner à la main
    build:
      context: https://github.com/dinoosauro/ffmpeg-web.git#main
    container_name: ffmpeg-web
    networks:
      - traefik-net
    ports:
      - "9831:3000"   # accès direct de secours (IP:port), le temps de mettre en place Technitium
      # - "3443:443" # Décommenter si tu actives le HTTPS
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ffmpeg-web.rule=Host(`ffmpeg-web.lab`)"
      - "traefik.http.services.ffmpeg-web.loadbalancer.server.port=3000"

networks:
  traefik-net:
    external: true
